#!/usr/bin/env bash

# TODO recursive

current_location=$(pwd)

images=$(find "$current_location" -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \))

selected_image=$(for img in $images; do
    relative_path="${img#$current_location/}"
    echo -en "$relative_path\0icon\x1f$img\n"
done | rofi -dmenu -i -p "$current_location" -theme ~/nix/stuff/rofi/s-img.rasi)

if [[ -n $selected_image ]]; then
    full_path="$current_location/$selected_image"
    
    action=$(echo -e "yazi\nopen\nyank\nrename\nyank path" | rofi -dmenu -i -theme ~/nix/stuff/rofi/launcher3.rasi)
    
    case $action in
        "yazi")
            yazi "$full_path"
            ;;
        "open")
            xdg-open "$full_path"
            ;;
        "yank")
            mime_type=$(file --mime-type -b "$full_path")
            wl-copy -t "$mime_type" < "$full_path"
            ;;
        "rename")
            new_name=$(rofi -dmenu -i -p "new name" -theme ~/.config/rofi/themes/launcher3.rasi -theme-str "listview { enabled: false;}")
            if [[ -n $new_name ]]; then
                extension="${full_path##*.}"
                mv "$full_path" "$(dirname "$full_path")/$new_name.$extension"
            fi
            ;;
        "yank path")
            echo -n "$full_path" | wl-copy
            ;;
        *)
            echo "exited"
            ;;
    esac
fi

