#!/usr/bin/env sh

wall_dir="$HOME/nix/stuff/wallpapers"
cache_dir="$HOME/.cache/bgselector"

mkdir -p "$cache_dir"

# Generate thumbnails
find "$wall_dir" -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp'\) | while read -r imagen; do
	filename="$(basename "$imagen")"
	thumb="$cache_dir/$filename"
	if [ ! -f "$thumb" ]; then
		magick "$imagen" -thumbnail x720^ -gravity center -extent 360x720 "$thumb"
	fi
done

# List wallpapers with icons for rofi
wall_selection=$(ls "$wall_dir" | while read -r A; do echo -en "$A\x00icon\x1f$cache_dir/$A\n"; done | sort | rofi -dmenu -config "$HOME/.config/rofi/bgselector.rasi")


# get current theme
themeline="$(cat ~/nix/mod/os/config.nix | grep 'theme = ')"
for name in {kanso,kantsi,macchiato,blacchiato,lix,everforest}; do
  if [[ $themeline == *"$name"* ]]; then 
    theme=$name
  fi
done


# set wallpaper and update wallpaper.json
if [ -n "$wall_selection" ]; then
	awww img "$wall_dir/$wall_selection" -t grow --transition-duration 1 --transition-fps 165
  cd $HOME/nix/theme
  echo $(cat wallpaper.json | jq ".$theme = \"$wall_selection\"") > wallpaper.json
	exit 0
else
	exit 1
fi

