#!/usr/bin/env dash

if $(awww query | grep "color: 000000"); then
  awww img $(~/nix/stuff/scripts/get_wall) \
    -t grow \
    --transition-duration 0.8 \
    --transition-fps 165
else
  awww clear
fi
