#!/usr/bin/env dash
# FIXME doesnt update the msg timestamp

msg="reminder at $(date -d '1200 seconds' +'%H:%H:%S' )"
echo "first $msg"

while true; do
  sleep 1200
  notify-send -t 1500 "dirnk water"
  echo "next $msg"
done
