[
  # (import ./gui/obs.nix)
  # (import ./gui/rofi.nix)
  # (import ./service/dbus.nix)
  # (import ./gui/dunst.nix)
  # (import ./gui/gtk.nix)
  # (import ./service/systemd.nix)
  # (import ./tui/ffmpeg.nix)
  (import ./gui/awww.nix)
  (import ./gui/foot.nix)
  (import ./gui/fuzzel.nix)
  (import ./gui/mpv.nix)
  # (import ./misc/pango.nix)
  (import ./gui/swayimg.nix)
  (import ./service/kanata.nix)
  (import ./service/mpd.nix)
  (import ./tui/eza.nix)
  (import ./tui/fastfetch.nix)
  (import ./tui/fd.nix)
  (import ./tui/gurk.nix)
  (import ./tui/luajit.nix)
  (import ./tui/ncmpcpp.nix)
  (import ./tui/nvim.nix)
  (import ./tui/ripgrep.nix)
  (import ./tui/skim.nix)
  (import ./tui/uutils.nix)
  (import ./tui/yazi.nix)

  (import ./tui/shell/nushell.nix)
  # rebuilds like 3000 packages?
  # (import ./tui/shell/bash.nix)
  # (import ./tui/shell/dash.nix)
  (import ./tui/shell/starship.nix)

  # (import ./gui/vicinae-extension-nix.nix)
  (import ./misc/keyb0xx.nix)
]
